clone:
  git:
    image: woodpeckerci/plugin-git:next

pipeline:
  lint:
    group: test
    image: golang:1.16
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: golang:1.16
    commands:
      - make test

  dryrun:
    image: thegeeklab/drone-docker-buildx:latest
    dockerfile: ./docker/Dockerfile.multiarch
    privileged: true
    dry_run: true
    repo: jasonlearst/plugin-git
    platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
    tags: latest
    secrets:
      - source: docker_username
        target: plugin_username
      - source: docker_token
        target: plugin_password
    when:
      event: pull_request

  build-next:
    image: thegeeklab/drone-docker-buildx:latest
    dockerfile: ./docker/Dockerfile.multiarch
    privileged: true
    repo: jasonlearst/plugin-git
    platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
    tags: next
    secrets:
      - source: docker_username
        target: plugin_username
      - source: docker_token
        target: plugin_password
    when:
      branch: master
      event: push

  build-tag:
    image: thegeeklab/drone-docker-buildx:latest
    dockerfile: ./docker/Dockerfile.multiarch
    privileged: true
    repo: jasonlearst/plugin-git
    platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
    tags: [latest, "${DRONE_TAG}"]
    secrets:
      - source: docker_username
        target: plugin_username
      - source: docker_token
        target: plugin_password
    when:
      event: tag