pipeline:
  lint:
    group: test
    image: golang:1.16
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: golang:1.16
    commands:
      - make test

  version:
    image: golang:1.16
    commands:
      - make version

  build-dryrun:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: woodpeckerci/plugin-git
      dockerfile: ./docker/Dockerfile.multiarch
      dry_run: true
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      tags: latest
    when:
      event: pull_request

  build-next:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: woodpeckerci/plugin-git
      dockerfile: ./docker/Dockerfile.multiarch
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      tags: next
    secrets: [docker_username, docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  build-tag:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: woodpeckerci/plugin-git
      dockerfile: ./docker/Dockerfile.multiarch
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      tags: [latest, "${CI_COMMIT_TAG}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag
