clone:
  git:
    image: plugins/git:next

pipeline:
  lint:
    group: test
    image: golang:1.16
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: golang:1.16
    commands:
      - make test

  build:
    image: golang:1.16
    commands:
      - make build

  dryrun:
    image: plugins/docker
    dockerfile: docker/Dockerfile.linux.amd64
    dry_run: true
    repo: woodpeckerci/plugin-git
    tags: latest
    when:
      event: pull_request

  publish-next:
    image: plugins/docker
    dockerfile: docker/Dockerfile.linux.amd64
    repo: woodpeckerci/plugin-git
    tags: next
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: push

  publish-tag:
    image: plugins/docker
    dockerfile: docker/Dockerfile.linux.amd64
    repo: woodpeckerci/plugin-git
    tags: [latest, "${DRONE_TAG}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag
