clone:
  git:
    image: woodpeckerci/plugin-git:next

pipeline:
  lint:
    group: test
    image: golang:1.16
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: golang:1.16
    commands:
      - make test

  dryrun:
    image: woodpeckerci/plugin-docker-buildx:latest
    dockerfile: ./docker/Dockerfile.multiarch
    privileged: true
    dry_run: true
    repo: woodpeckerci/plugin-git
    platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
    tags: latest
    secrets: [docker_username, docker_password]
    when:
      event: pull_request

  build-next:
    image: woodpeckerci/plugin-docker-buildx:latest
    dockerfile: ./docker/Dockerfile.multiarch
    privileged: true
    repo: woodpeckerci/plugin-git
    platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
    tags: next
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: push

  build-tag:
    image: woodpeckerci/plugin-docker-buildx:latest
    dockerfile: ./docker/Dockerfile.multiarch
    privileged: true
    repo: woodpeckerci/plugin-git
    platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
    tags: [latest, "${DRONE_TAG}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag