variables:
  - &golang 'golang:1.18-alpine'

pipeline:
  version:
    group: prepare
    image: *golang
    commands:
      - apk add make
      - make version

  vendor:
    group: prepare
    image: *golang
    commands:
      - go mod vendor

  lint:
    group: test
    image: *golang
    commands:
      - apk add make
      - make vet
      - make formatcheck

  test:
    group: test
    image: *golang
    commands:
      - apk add make git-lfs
      - make test

  build-dryrun:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: woodpeckerci/plugin-git
      dockerfile: ./docker/Dockerfile.multiarch
      dry_run: true
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      tags: latest
    when:
      event: pull_request

  release-next:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: woodpeckerci/plugin-git
      dockerfile: ./docker/Dockerfile.multiarch
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      tags: next
    secrets: [docker_username, docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  release-tag:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: woodpeckerci/plugin-git
      dockerfile: ./docker/Dockerfile.multiarch
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      tags: [latest, "${CI_COMMIT_TAG}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag

  build-binarys:
    image: *golang
    commands:
      - apk add make
      - make release
    when:
      event: tag

  release-binarys:
    image: plugins/github-release
    settings:
      files:
        - release/*
      title: ${CI_COMMIT_TAG##v}
      api_key:
        from_secret: github_token
    when:
      event: tag
