FROM --platform=$BUILDPLATFORM golang:1.18 AS build
ARG TARGETOS TARGETARCH

WORKDIR /src
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    make build

FROM alpine:edge
ARG HOME=/app

RUN mkdir -p $HOME
RUN apk add --no-cache ca-certificates git openssh curl git-lfs
ENV GODEBUG=netdns=go
ENV PLUGIN_HOME=$HOME

COPY --from=build src/release/plugin-git /bin/
ENTRYPOINT [ "sh", "-c", "/bin/plugin-git" ]
