FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25 AS build
ARG TARGETOS TARGETARCH

WORKDIR /src
COPY . .

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        make \
        ca-certificates \
        curl \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN make build

FROM docker.io/library/debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        git-lfs \
        openssh-client \
        ca-certificates \
        curl \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ARG HOME=/app

ENV GODEBUG=netdns=go
ENV PLUGIN_HOME=$HOME

RUN mkdir -p $HOME

COPY --from=build /src/release/plugin-git /bin/

ENTRYPOINT ["/bin/plugin-git"]
