FROM --platform=$BUILDPLATFORM golang:1.16 AS build

WORKDIR /src
COPY . .
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    make build

FROM alpine:3.15
RUN apk add --no-cache ca-certificates git openssh curl
ENV GODEBUG=netdns=go

COPY --from=build src/release/plugin-git /bin/
ENTRYPOINT ["/bin/plugin-git"]
